config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  resources :rsvps

  root 'pages#index'

  resources :gifts, only: [:index]

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  validates :name, presence: true
  validates :cost_cents, presence: true
  validates :url, presence: true, uniqueness: true

  URL_PREFIX = 'https://wanderable.com'.freeze

  TOTAL_COST_CENTS = {
    '/cart/86296/add?item_id=86296' => 3000_00,
    '/cart/86305/add?item_id=86305' => 2500_00,
    '/cart/86291/add?item_id=86291' => 180_00,
    '/cart/86279/add?item_id=86279' => 250_00,
    '/cart/86292/add?item_id=86292' => 240_00,
    '/cart/86301/add?item_id=86301' => 400_00,
    '/cart/86293/add?item_id=86293' => 205_00,
    '/cart/86295/add?item_id=86295' => 780_00
  }.freeze

  def self.total_cost_for_url url
    TOTAL_COST_CENTS.each do |url_stub, cost_in_cents|
      if url.include?(url_stub)
        return cost_in_cents
      end
    end
  end

  # Returns the cost to fund this gift, in dollars.
  def cost
    return unless cost_cents
    BigDecimal.new(cost_cents.to_s) / 100
  end

  # Returns the amount remaining to fully fund this gift, in dollars.
  def amount_remaining
    return unless cost_cents && amount_received_cents
    remaining_cents = cost_cents - amount_received_cents
    BigDecimal.new(remaining_cents.to_s) / 100
  end

  # Returns the amount of money already received to fund this gift, in dollars.
  def amount_received
    return unless amount_received_cents
    BigDecimal.new(amount_received_cents.to_s) / 100
  end

  def unfunded?
    amount_received_cents.nil? || amount_received_cents.zero?
  end

  # Returns a value between 0-100 representing how fully this gift is funded.
  def percent_funded
    if amount_received_cents
      ratio = BigDecimal.new(amount_received_cents.to_s) / cost_cents
      (ratio * 100).to_i
    else
      0
    end
  end
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  after_create :send_emails

  scope :attending, ->{ where(attending: true) }

  scope :not_attending, ->{ where(attending: false) }

  validates :first_name, presence: true
  validates :guest_count, presence: true,
                          numericality: {only_integer: true, greater_than: -1}
  validate :not_attending_zero_guest_count

  def self.total_guest_count
    attending.pluck(:guest_count).sum
  end

  def self.total_not_attending
    not_attending.count
  end

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def send_emails
    User.all.each do |user|
      RsvpMailer.repondez(self, user.email).deliver
    end
  end

  private

  def not_attending_zero_guest_count
    if guest_count && guest_count.nonzero? && !attending
      errors.add(:guest_count, 'must be zero if you are not attending.')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    email.split('@').first
  end
end

app/models/wanderable.rb
class Wanderable
  attr_reader :agent, :url

  def initialize url
    @agent = Mechanize.new do |agent|
      agent.user_agent_alias = 'Mac Safari'
      agent.max_history = 0
      agent.keep_alive = false
      agent.ssl_version = 'SSLv3'
      agent.verify_mode = OpenSSL::SSL::VERIFY_NONE
    end
    @url = url
  end

  def scrape_gifts
    page = @agent.get(@url)
    page.at('#hm-list').search('.hm-panel .item').each do |gift_html|
      extract_gift(gift_html)
    end
  end

  private

  def extract_gift gift_html
    image_url = gift_html.at('.col-sm-8 img')['src']
    name = gift_html.at('.details h2').text
    details = gift_html.search('.details p').map {|p| p.text }.
                                        reject {|txt| txt.blank? }
    case details.size
    when 2
      description, location = details
    when 1
      location = details.first
    else
      description = details.join("\n").presence
    end
    cost_str = gift_html.at('.col-sm-4 p').text
    relative_url = gift_html.at('.col-sm-4 a.add_to_cart')['href']
    unless relative_url.start_with?('http')
      url = Gift::URL_PREFIX + relative_url
    end
    gift = Gift.where(url: url).first_or_initialize
    gift.name = name
    gift.description = description
    gift.location = location
    gift.image_url = image_url
    gift.url = url
    if cost_str.present?
      dollars = BigDecimal.new(Monetize.parse(cost_str).to_s)
      cents_remaining = (dollars * 100).to_i
      if total_cents=Gift.total_cost_for_url(relative_url)
        gift.cost_cents = total_cents
        gift.amount_received_cents = total_cents - cents_remaining
      end
    end
    gift.save
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  # GET /gifts.json
  def index
    wanderable = Wanderable.new(ENV['WANDERABLE_URL'])
    wanderable.scrape_gifts
    @gifts = Gift.order(:name)
    respond_to do |format|
      # Don't render full page layout if this is an AJAX request
      format.html { render layout: !request.xhr? }
      format.json
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /
  def index
    @gifts = Gift.order(:name)
    @rsvp = Rsvp.new(guest_count: 0, attending: true)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    redirect_to root_path
  end

  def create
    redirect_to root_path
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  layout 'admin'
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:create]

  # GET /rsvps
  # GET /rsvps.json
  def index
    @rsvps = Rsvp.all
    @total_guest_count = Rsvp.total_guest_count
    @total_not_attending = Rsvp.total_not_attending
  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
  end

  # GET /rsvps/new
  def new
    @rsvp = Rsvp.new(guest_count: 0)
  end

  # GET /rsvps/1/edit
  def edit
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(rsvp_params)
    respond_to do |format|
      if @rsvp.save
        format.html {
          redirect_to root_path, notice: 'RSVPed!'
        }
        format.json { render :show, status: :created, location: @rsvp }
      else
        format.html {
          flash[:warning] = 'There was a problem with your RSVP. Please try again: ' + @rsvp.errors.full_messages.join(', ')
          redirect_to root_path
        }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rsvps/1
  # PATCH/PUT /rsvps/1.json
  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp.destroy
    respond_to do |format|
      format.html { redirect_to rsvps_url, notice: 'Rsvp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsvp_params
      params.require(:rsvp).permit(:first_name, :last_name, :email, :guest_count, :attending, :song_suggestion)
    end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/gifts/_list.html.erb
<% if gifts.count.nonzero? %>
  <ul class="gifts-list">
    <% gifts.each do |gift| %>
      <li>
        <div class="row">
          <div class="col-md-7 text-center">
            <div class="gift-details">
              <% if gift.image_url.present? %>
                <p>
                  <%= link_to image_tag(gift.image_url, alt: '', class: 'gift-image'), gift.url %>
                </p>
              <% end %>
              <%= link_to gift.name, gift.url, title: "#{number_to_currency gift.amount_remaining} remaining", data: {toggle: "tooltip", placement: 'bottom'} %>
              <% if gift.description.present? %>
                <p class="gift-description">
                  <%= gift.description %>
                </p>
              <% end %>
              <% if gift.location.present? %>
                <p class="gift-location">
                  <%= gift.location %>
                </p>
              <% end %>
            </div>
          </div>
          <div class="col-md-5 text-center">
            <% unless gift.unfunded? %>
              <p class="gift-percent-funded">
                <%= number_to_percentage gift.percent_funded, precision: 0 %>
                funded
              </p>
            <% end %>
            <div id="gift-thermometer-<%= gift.id %>" class="gift-thermometer thermometer horizontal <%= 'unfunded' if gift.unfunded? %>">
              <div class="track">
                <div class="progress" data-percent="<%= gift.percent_funded %>">
                  <div class="amount"></div>
                </div>
              </div>
            </div>
            <%= link_to 'Contribute to this gift!', gift.url, class: 'contribute-link', title: "#{number_to_currency gift.amount_remaining} remaining", data: {toggle: "tooltip", placement: 'bottom'} %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_notifications.html.erb
<% if (warning=flash[:warning]).present? || notice.present? || alert.present? %>
  <div class="notifications-container text-center">
    <% if warning.present? %>
      <div class="alert alert-danger">
        <%= warning %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-warning">
        <%= alert %>
      </div>
    <% end %>
    <% if notice.present? %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Kristen and Todd are getting married!</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="admin <%= controller.controller_name %> <%= controller.action_name %>">
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Wedding Admin', rsvps_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'RSVPs Admin', rsvps_path %>
            </li>
            <li>
              <%= link_to 'Public Site', root_path %>
            </li>
            <li>
              <%= link_to "Signed in as #{current_user.name}", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= render 'layouts/notifications' %>
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kristen and Todd are getting married!</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %> <%= controller.action_name %>">
  <%= render 'layouts/notifications' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/pages/index.html.erb
<section id="intro">
  <div class="sky"></div>
  <div class="foreground">
    <div class="fireflies"><div class="firefly"></div></div>
    <%= image_tag("intro/bush.png", class: "bush scenery") %>
    <div class="fireflies"><div class="firefly"></div></div>
  </div>
  <div class="midground">
    <%= image_tag("intro/fire.png", class: "fire scenery") %>
    <%= image_tag("intro/bush.png", class: "bush-front scenery") %>
    <div class="fireflies"><div class="firefly"></div></div>
    <%= image_tag("intro/bush.png", class: "bush-back scenery") %>
      <div class="fireflies"><div class="firefly"></div></div>
    <%= image_tag("intro/tent.png", class: "tent scenery") %>
  </div>
  <div class="background">
    <div class="fireflies"><div class="firefly"></div></div>
    <%= image_tag("intro/bush.png", class: "bush scenery") %>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="fireflies"><div class="firefly"></div>
        </div>
        <nav id="sign-nav">
          <ul>
            <li class="sign">
              <a id="logo" href="#">Kristen and Todd Get Married!</a>
            </li>
            <li class="sign">
              <a href="#story">Our Story</a>
            </li>
            <li class="sign">
              <a href="#location">Directions</a>
            </li>
            <li class="sign">
              <a href="#rsvp">RSVP</a>
            </li>
            <li class="sign">
              <a href="#registry">Registry</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</section>

<section id="story">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="section-header">Our Story</h2>
        <div class="slider single-item">
          <div class="text_background">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <p>
                  <span class="todd">Todd</span> and <span class="kristen">Kristen</span> first met years ago through mutual friends. After meeting several times they realized they had many things in common, such as a fondness for Dwight Yoakam songs.
                </p>
                <p>
                  <span class="todd">Todd</span> decided to ask <span class="kristen">Kristen</span> on a date. He was nervous, but determined.
                </p>
              </div>
            </div>
          </div>
          <div><%= image_tag("story/firstdate.jpg", class: "comsize") %></div>
          <div class="text_background">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <p>
                  That weekend they watched X-Men: First Class and ate California tart frozen yogurt at Fro-Jo's. They sat on a blanket under the stars and shared stories.
                </p>
                <p>
                  For one reason or another <span class="todd">Todd</span> and <span class="kristen">Kristen</span> drifted. However, it was clear there was something between them.
                </p>
                <p>
                  A couple of months later some of their friends planned a trip to a corn maze and invited <span class="todd">Todd</span> and <span class="kristen">Kristen</span> along. They had a great time. That night they carved pumpkins together.
                </p>
                <p>
                  Once more <span class="todd">Todd</span> asked <span class="kristen">Kristen</span> on a date.
                </p>
              </div>
            </div>
          </div>
          <div><%= image_tag("story/secondfirstdate.jpg", class: "comsize") %></div>
          <div class="text_background">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <p>
                  <span class="todd">Todd</span> and <span class="kristen">Kristen</span> went on many more dates and spent countless hours together. Soon it was <span class="love">LOVE</span>. The two went on camping trips, visited new places, played video games, and watched lots of TV shows.
                </p>
                <p>
                  One day <span class="todd">Todd</span> and <span class="kristen">Kristen</span> were sitting in the living room with <span class="artemus">Artemus</span>.
                </p>
              </div>
            </div>
          </div>
          <div><%= image_tag("story/artemuspredictsthefuture.jpg", class: "comsize") %></div>
          <div class="text_background">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <p>
                  After that things became more serious. Sometime later <span class="todd">Todd</span> and <span class="kristen">Kristen</span> took a trip to Boston. The day before they left for home <span class="todd">Todd</span> took <span class="kristen">Kristen</span> on a walk through a beautiful Boston park.
                </p>
              </div>
            </div>
          </div>
          <div><%= image_tag("story/theproposal.jpg", class: "comsize") %></div>
          <div class="text_background">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <p>
                  And they are still having adventures.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="location">
  <%= image_tag("location/fields.png", class: "fields scenery") %>
  <div class="scenery fields-foreground"></div>
  <%= image_tag("location/tree.png", class: "tree scenery") %>
  <div class="scenery directions container">
    <div class="row">
      <div class="col-md-6">
        <h2 class="subheader">September <span class="big-text">21</span> 2014</h2>
      </div>
      <div class="col-md-6">
        <h2 class="subheader">Moonlight Fields Farm<br/>5028 Ashgrove Road<br/>Nicholasville, KY</h2>
      </div>
    </div>
    <div class="row sign-row">
      <div class="col-md-6">
      </div>
      <div class="col-md-6 sign-post">
        <div class="sign">
          <p><a href="#" data-toggle="modal" data-target="#mapModal">Map</a></p>
          <p><a href="#" data-toggle="modal" data-target="#directionsModal">Directions</a></p>
          <p><a href="#" data-toggle="modal" data-target="#hotelsModal">More Information</a></p>
        </div>
      </div>
    </div>
  </div>
  <div id="mapModal" class="modal fade" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        </div>
        <div class="modal-body">
          <h2>Moonlight Fields</h2>
            <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?sll=37.93159,-84.495405&amp;sspn=0.0064991,0.0109864&amp;cid=16633015249682357321&amp;q=Moonlight+Fields&amp;ie=UTF8&amp;hq=&amp;hnear=&amp;ll=37.93159,-84.495405&amp;spn=0.006295,0.006295&amp;t=m&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?sll=37.93159,-84.495405&amp;sspn=0.0064991,0.0109864&amp;cid=16633015249682357321&amp;q=Moonlight+Fields&amp;ie=UTF8&amp;hq=&amp;hnear=&amp;ll=37.93159,-84.495405&amp;spn=0.006295,0.006295&amp;t=m&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:left">View Larger Map</a></small>
        </div>
      </div>
    </div>
  </div>
  <div id="directionsModal" class="modal fade" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        </div>
        <div class="modal-body">
        <p><b><center>From the north on I-75</center></b></p>
        <p>When traveling on I-75 S, take exit 115 to KY-922/Newtown Pike exit toward Airport/Lexington</p>
        <p>Take the New Circle Rd/KY-4 W ramp to New Circle Road</p>
        <p>Take exit 19 to Nicholasville Rd/US-27 toward Nicholasville/Lexington</p>
        <p>Turn right onto Nicholasville Rd</p>
        <p>Turn left onto Ashgrove Rd, just past the Brannon Crossing shopping center</p>
        <p>Moonlight Fields Farm will be on the left</p>
        <p><b><center>From the east on I-64</center></b></p>
        <p>When traveling on I-64 W, take exit 87 to KY-859/Haley Rd toward Bluegrass Station</p>
        <p>Turn left onto Haley Rd</p>
        <p>Turn right onto Winchester Rd</p>
        <p>Turn left onto Man O War Blvd</p>
        <p>Turn left onto Tates Creek Rd</p>
        <p>Turn right onto Ashgrove Rd</p>
        <p>Moonlight Fields Farm will be on the right</p>
        </div>
      </div>
    </div>
  </div>
  <div id="hotelsModal" class="modal fade" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          </div>
          <div class="modal-body">
            <p><b>Hotels</b></p>
            <p><a href="http://www.expedia.com/Nicholasville-Hotels-Comfort-Inn.h6648831.Hotel-Information?chkin=09%2F20%2F2014&chkout=09%2F21%2F2014&rm1=a2&hwrqCacheKey=6e9374ae-3283-4c90-b61e-9e8611f46e38HWRQ1404255689815&c=bf64773f-72ca-4f9e-ba77-cfb093561164&">Comfort Inn</a></p>
            <p><a href="http://www.cornerhousebedandbreakfast.com/">Corner House Bed & Breakfast</a></p>
            <p><a href="http://www.expedia.com/Nicholasville-Hotels-Holiday-Inn-Express-Nicholasville.h424216.Hotel-Information?chkin=09%2F20%2F2014&chkout=09%2F21%2F2014&rm1=a2&hwrqCacheKey=6e9374ae-3283-4c90-b61e-9e8611f46e38HWRQ1404255689815&c=bf64773f-72ca-4f9e-ba77-cfb093561">Holiday Inn Express Nicholasville</a><p>
            <p><a href="http://www.expedia.com/Nicholasville-Hotels-Howard-Johnson-Inn-Nicholasville-Lexington.h213065.Hotel-Information?chkin=09%2F20%2F2014&chkout=09%2F21%2F2014&rm1=a2&hwrqCacheKey=6e9374ae-3283-4c90-b61e-9e8611f46e38HWRQ1404255689815&c=bf64773f-72ca-4f9e-ba77-">Howard Johnson Inn</a><p>
            <p><b>Activities</b></p>
            <p><a href="http://www2.ca.uky.edu/arboretum/">The Arboretum</a></p>
            <p><a href="http://www.arcadiumbar.com/">The Arcadium Arcade Bar</a></p>
            <p><a hreef="http://www.bleuplatetours.com/lexington-food-tours.html">Blue Plate Walking Tour</a></p>
            <p><a href="http://www.lexingtonky.gov/index.aspx?page=239">Latino Festival</a></p>
            <p><a href="http://www.lexingtonfarmersmarket.com/">Lexington Farmer's Market</a></p>
            <p><b>Restaurants</b></p>
            <p><a href="http://www.asukagrill.com/">Asuka Japanese Steakhouse & Sushi</a></p>
            <p><a href="http://giuseppeslexington.com/">Giuseppe's Italian Restaurant</a></p>
            <p><a href="http://www.urbanspoon.com/r/65/1579406/restaurant/Lexington/Nicholasville-Road-Area/Panera-Bread-Nicholasville">Panera</a></p>
            <p><a href="http://www.urbanspoon.com/r/65/1491385/restaurant/Lexington/Nicholasville-Road-Area/Red-Robin-Gourmet-Burgers-Nicholasville">Red Robin</a></p>
            </div>
        </div>
      </div>
  </div>
</section>

<section id="rsvp">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2 class="section-header">RSVP</h2>
        <%= render 'rsvps/form' %>
      </div>
    </div>
  </div>
</section>

<section id="registry">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="section-header">Registry</h2>
        <div id="gifts-list-wrapper" data-url="<%= gifts_url %>">
          <%= render 'gifts/list', gifts: @gifts %>
        </div>
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <p>
              Honeymoon registry provided by <%= link_to 'Wanderable', ENV['WANDERABLE_URL'] %>.
            </p>
            <%= link_to image_tag('wanderable.jpg', class: 'wanderable-image', alt: 'Wanderable'), ENV['WANDERABLE_URL'], target: '_blank', class: 'wanderable-link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div id="footer">
      <p>Congratulations Kristen and Todd! Site built by <a href="http://lexladiescode.org/">LexLadiesCoding Club</a> 2014</p>
</div>

app/views/rsvps/edit.html.erb
<h1>Edit RSVP</h1>

<%= render 'form' %>

<hr>

<div class="text-right">
  <%= button_to 'Delete RSVP', @rsvp, data: {confirm: 'Are you sure you want to delete this RSVP?'}, method: :delete, class: 'btn btn-small btn-danger' %>
</div>

app/views/rsvps/index.html.erb
<ul class="list-inline">
  <li><%= pluralize @total_guest_count, 'guest' %> attending</li>
  <li><%= pluralize @total_not_attending, 'person' %> not attending</li>
  <li><%= pluralize Rsvp.count, 'RSVP' %></li>
</ul>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th># guests</th>
      <th>Attending?</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @rsvps.each do |rsvp| %>
      <tr>
        <td><%= rsvp.full_name %></td>
        <td><%= mail_to rsvp.email, rsvp.email %></td>
        <td><%= rsvp.guest_count %></td>
        <td><%= rsvp.attending? ? 'yes' : 'no' %></td>
        <td>
          <ul class="list-inline">
            <li><%= link_to 'View', rsvp %></li>
            <li><%= link_to 'Edit', edit_rsvp_path(rsvp) %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Make a new RSVP', new_rsvp_path, class: 'btn btn-default' %></p>

app/views/rsvps/new.html.erb
<%= render 'form' %>

app/views/rsvps/show.html.erb
<dl class="dl-horizontal">
  <dt>First name:</dt>
  <dd><%= @rsvp.first_name %></dd>
  <dt>Last name:</dt>
  <dd><%= @rsvp.last_name %></dd>
  <dt>Email address:</dt>
  <dd><%= mail_to @rsvp.email, @rsvp.email %></dd>
  <dt>Attending?</dt>
  <dd><%= @rsvp.attending? ? 'yes' : 'no' %></dd>
  <dt># guests:</dt>
  <dd><%= @rsvp.guest_count %></dd>
  <dt>Song suggestion:</dt>
  <dd>
    <% if (suggestion=@rsvp.song_suggestion).present? %>
      <%= suggestion %>
    <% else %>
      &mdash;
    <% end %>
  </dd>
  <dt>Date RSVPed:</dt>
  <dd><%= @rsvp.created_at %></dd>
</dl>

<p>
  <%= link_to 'Edit RSVP', edit_rsvp_path(@rsvp), class: 'btn btn-default' %>
</p>